// https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
= Kerberos SSO & Active Directory in 2023 {revnumber}
:author: Y0d0g MiMiMi
:email: github@stippmilch.de
:revnumber: v1.0
:revdate: 2023-07-24 12:32:06
:lang: en
:imagesdir: img
:doctype: article
:homepage: https://github.com/grepmeister/checkmk-kerberos-howto/blob/main/kerberos_howto.adoc
:toc: left
:sectnums:
:numbered:
:icons: font
:sectanchors:
:experimental:
:source-highlighter: rouge
:rouge-linenums-mode: inline

:SP: pass:quotes[*ServicePrincipal (SP)*]
:AD: pass:quotes[*Active Directory (AD)*]
:KDC: pass:quotes[*Key Distribution Center (KDC)*]
:KRB: pass:quotes[*Kerberos Single sign-on (SSO)*]
:KR: pass:quotes[*Kerberos Realm*]
:DC: pass:quotes[*Domain Controller (DC)*]
:MY-SP: HTTP/monitoring.it.mycompany.tld
// is there is a asciidoctor offline documentation ?

I failed to set up {KRB} for Checkmk and {AD} using the https://docs.checkmk.com/latest/en/kerberos.html["Kerberos is not officially supported by Checkmk"] document. +

It's not complete as of https://github.com/Checkmk/checkmk-docs/blob/27fcad0191f44c0401f61227098e932597438226/en/kerberos.asciidoc[2023-07-18]. +
I guess this is why it's not officially supported.

I noticed that not only me but also other Checkmk users failed to set Kerberos up. +
So I decided to write this HowTo. +

[TIP]
====
* The source of this document is located here: {homepage} 
* Please open github https://github.com/grepmeister/checkmk-kerberos-howto/issues/new[issues] or pull request to improve the document.
====

The https://docs.checkmk.com/latest/en/saml.html?lquery=saml#heading__configuration_of_apache[SAML] document introduced for checkmk 2.2. helped a lot to get the apache config settings right. +
I am using Windows Server 2019 and Checkmk 2.1 while writing this document.

//[cols="1,1"]
.Example Environment used in this document:
|===
| Item | Example in this document | Note

| {KR} | IT.MYCOMPANY.TLD | Always upper case. 
| {SP} | HTTP/monitoring.it.mycompany.tld | ⚠️  It's *HTTP* not *HTTPS*.
| Monitoring Server URL | https://monitoring.it.mycompany.tld |
| AD Service User | svc_http_prod | In {AD} you have to map a {SP} to a user object.
| {DC} | ad.mycompany.tld | acts as {KDC}
| Checkmk Site | prod | the checkmk site 
|===

== What needs to be done ?

* We need to set up a trust relationship between the Checkmk Server and the {AD} once by creating a kerberos keytab file.
* A keytabfile contains a kind of shared secret.
* To create the keytabfile we will either use *msktutil* on Linux icon:linux[] or *ktpass.exe* on Windows icon:windows[].
* We will need a domain user to map the {SP} to.
** On Windows you have to create the user manually first.
** msktutil will create the user it on it's own for you.
* Finaly we have to adjust the apache configuration to use the Kerberos auth.conf

== Prerequisite

* Your checkmk is reachable by a FQDN and uses https (see https://docs.checkmk.com/latest/en/omd_https.html[Securing the web interface with HTTPS]).
* Your Web Browsers trust your checkmk server's FQDN. (see <<browser-settings>> below)
* You have got a Kerberos Ticket Granting Tickets (TGT) (kinit <AD-User>, klist, on Windows you get it automatically on Domain login)
* Keep in mind that usually your {AD} Servers first have to sync. It can take up to 15min until all Servers know about the new user and the SPN mapping.

[#krb5-conf]
=== Set up /etc/krb5.conf

* On Linux most kerberos related tools an libraries honor the /etc/krb5.conf
* Therefore I use this minimal /etc/krb5.conf:

./etc/krb5.conf
[source,linenums]
----
[libdefaults]
default_realm = IT.MYCOMPANY.TLD <1>

dns_lookup_kdc = false
dns_uri_lookup = false

[realms]
IT.MYCOMPANY.TLD = {
  kdc = ad.mycompany.tld <2>
}

[domain_realm]
.mycompany.tld = IT.MYCOMPANY.TLD <3>
mycompany.tld = IT.MYCOMPANY.TLD <4>
----
<1> replace with your {KR}
<2> replace with your {AD}
<3> map your DNS domain to your {KR}
<4> map your DNS domain to your {KR}

=== On Windows

* Windows Servers usually already know everything about their kerberos domain. No need to configure anything.

== Create the keytab file

* I usually use msktutil to create a keytab containing the {SP}, because it is easy and just works.
* But since msktutil is not available on the Checkmk Applinace I will also explain how to
get a keytabfile with the Windows tool ktpass.exe (which has got some pitfalls).

=== Create the keytab file with msktutil on linux

TIP: You have to adjust some values to match your environment.

This will create the keytab file.

.msktutil.sh
[source,bash,linenums]
----
#!/bin/bash

msktutil \
	create \
	--server ad.mycompany.tld \ <1>
	--description "Created by $USER on $(date +%F)" \
	--dont-expire-password \
	--no-pac \
	--no-reverse-lookups \
	--user-creds-only \
	--use-service-account \
	--keytab svc_http_prod.keytab \ <2>
	--account-name svc_http_prod \
	--realm IT.MYCOMPANY.TLD \ <3>
  --enctypes 0x10 \ <4>
	--service HTTP/remote.jodok.tribe29.com
----
<1> use one of your active directory servers
<2> the name of your keytab file
<3> your kerberos realm
<4> aes256-cts-hmac-sha1
<5> your {SP} in the form *HTTP/<FQDN>*

=== Create keytab file with ktpass.exe on windows


.User
* create a user account in active directory e.g. svc_http_prod with these attributes:
** User login name: svc_http_prod
** Password: Choose a random password, we will set it to random later anyhow.
* Next
** [x] User cannot change password
** [x] Passwod never expires
* Account > Account Options:
** This account supports Kerberos AES 256 bit encryption.


.Keytab
* open an cmd.exe *as Administrator*
* I use AES256-CTS-HMAC-SHA1-96 because I believe that this is state of the art.

----
ktpass ^
   -princ HTTP/remote.jodok.tribe29.com@JODOK.TRIBE29.COM ^
   -mapuser svc_http_cmk_prod@JODOK.TRIBE29.COM ^
   -out z:\svc_http_remote.keytab ^
   -ptype KRB5_NT_PRINCIPAL ^
   -crypto AES256-SHA1 ^
   +rndPass
----


WARNING: it can take up to n minutes that this gets replicated to your other domain controllers.

=== Verify the keytab file and SP in AD 

* since we setup <<krb5-conf>> we can now use tools like kinit, klist, kvno 

klist ...
kinit
kvno

=== Install the keytab file

* /omd/sites/${SITE}/etc/apache/svc_http_prod.keytab
* cp
* chown
* chmod

== Apache Config

* As site user

.move away cookie_auth.conf, we do not need it
[source,bash]
----
mv -v ~/etc/apache/conf.d/cookie_auth.conf ~/cookie_auth.conf.bak
----

.New Apache Config $HOME/etc/apache/conf.d/auth.conf
[source,apache,linenums]
----
Define SITE prod
#           ^^^^ <1>

Define REALM IT.MYCOMPANY.TLD
#            ^^^^^^^^^^^^^^^^ <2>

<IfModule !mod_auth_kerb.c>
   LoadModule auth_kerb_module /usr/lib/apache2/modules/mod_auth_kerb.so
   #                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ <3>
</IfModule>

<Location /${SITE}>

  # Use Kerberos auth only in case there is no Checkmk authentication
  # cookie provided by the user and whitelist also some other required URLs

  <If "! %{HTTP_COOKIE} =~ /^(.*;)?auth_${SITE}/ && \
    ! %{REQUEST_URI} = '/${SITE}/check_mk/register_agent.py' && \
    ! %{REQUEST_URI} = '/${SITE}/check_mk/deploy_agent.py' && \
    ! %{REQUEST_URI} = '/${SITE}/check_mk/run_cron.py' && \
    ! %{REQUEST_URI} = '/${SITE}/check_mk/restapi.py' && \
    ! %{REQUEST_URI} = '/${SITE}/check_mk/automation.py' && \
    ! %{REQUEST_URI} -strmatch '/${SITE}/check_mk/api/*' && \
    ! %{REQUEST_URI} = '/${SITE}check_mk/ajax_graph_images.py' && \
    ! %{QUERY_STRING} =~ /(_secret=|auth_|register_agent)/ && \
    ! %{REQUEST_URI} =~ m#^/${SITE}/(omd/|check_mk/((images|themes)/.*\.(png|svg)|login\.py|.*\.(css|js)))# ">

    Order allow,deny
    Allow from all

    Require valid-user

    AuthType Kerberos
    AuthName "Checkmk AD Kerberos Login"
    KrbMethodNegotiate on
    KrbMethodK5Passwd off
    KrbLocalUserMapping on
    KrbSaveCredentials off

    # Environment specific: Path to the keytab, REALM and ServicePrincipal
    Krb5Keytab /omd/sites/${SITE}/etc/apache/svc_http_prod.keytab
    #          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ <3>

    KrbServiceName HTTP/monitoring.it.mycompany.tld@IT.MYCOMPANY.TLD
    #              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ <4>
    KrbAuthRealm ${REALM}
 
    ErrorDocument 401 '<html> \
      <head> \
        <meta http-equiv="refresh" content="1; URL=/${SITE}/check_mk/login.py"> \
      </head> \
      <body> \
        Kerberos authentication failed, redirecting to login page. \
        <a href="/${SITE}/check_mk/login.py">Click here</a>. \
      </body> \
    </html>'

  </If>

</Location>

# These files are accessible unauthenticated (login page and needed ressources)
<LocationMatch /${SITE}/(omd/|check_mk/(images/.*\.png|login\.py|.*\.(css|js)))>
  Order allow,deny
  Allow from all
  Satisfy any
</LocationMatch>
----
<1> add your checkmk site name (instance) 
<2> add your {KR}
<3> add your {SP} {MY-SP}

[#browser-settings]
== Browser Settings

=== Firefox

* Configuring Firefox for Negotiate Authentication
* Enter you DNS Domain for which you want to use kerberos.
----
about: config
network.negotiate-auth.trusted-uris: .it.example.tld
----

* Firefox will then send a HTTP Header to the Checkmk Server that signals the apache, that it can do Kerberos.

=== Google Chrome

* On Windows EDGE usually already trusts your DNS domain.

=== Microsoft EDGE

* On Windows EDGE usually already trusts your DNS domain.

=== Safari

* I have no clue. But Safari can do Kerberos SSO as well. Somehow.

=== Curl

* curl can do negotate autentication
* make sure you have a valid tgt ticket.
----
curl --negotiate --user : https://monitoring.it.company.tld/prod/
----

== Summary

* In the original document there are some stars a in the apache configuration to highlight that they need to be customized, but users did not replace them.
* The location of the keytab /etc/krb5.keytab makes not make much sense, since it only needs and only should be readable by the site apache.
* 

== Problems

* increasing the apache debug level does not help much instead run it in the foreground apache -X 
* You recreated the ServicePrincipal and keytab but you are still working with the old Service Ticket: kdestroy, kinit <username>
* +KrbSaveCredentials on+ makes no sense for Checkmk and could be a security weakness.

== Asciidoctor 

NOTE: NOTE An admonition draws the reader's attention to auxiliary information.

IMPORTANT: IMPORTANT Don't forget the children!

TIP: TIP Look for the warp zone under the bridge.

CAUTION: Slippery when wet.

WARNING: The software you're about to use is untested.

IMPORTANT: Sign off before stepping away from your computer.


